apiVersion: v1 # Descriptor conforms to version v1 of Kubernetes API
kind: Pod # Select Pod resource
metadata:
  name: hello-kube # The name of the pod
spec:
  containers:
    - image: hello-kubeima # Image to create the container
      name: hello-kube # The name of the container
      ports:
        - containerPort: 3001 # The port the app is listening on
          protocol: TCP
