apiVersion: v1
kind: ReplicationController
metadata:
  name: hello-rc
spec:
  replicas: 2 # number of the pod
  selector: # The pod selector determining what pods the RC is operating on
    app: hello-kube # label value
  template: # pod template
    metadata:
      labels:
        app: hello-kube # label value
    spec:
      containers:
        - image: yukino1710193/hello-kubeima:latest # image used to run container
          name: hello-kube # name of the container
          ports:
            - containerPort: 3001 # pod of the container
