apiVersion: v1
kind: Pod
metadata:
  name: application
spec:
  containers:
    - image: yukino1710193/hello-service:latest
      name: application
      ports:
        - containerPort: 6379
          protocol: TCP